// <auto-generated />
using System;
using BulkyBook.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyBook.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250516080821_addForeignKeyForCategoryProductRelation")]
    partial class addForeignKeyForCategoryProductRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyBook.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action",
                            DisplayOrder = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "SciFi",
                            DisplayOrder = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "History",
                            DisplayOrder = 3
                        });
                });

            modelBuilder.Entity("BulkyBook.Models.Product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("listPrice")
                        .HasColumnType("float");

                    b.Property<double>("priceProduct")
                        .HasColumnType("float");

                    b.Property<double>("priceProductFor100")
                        .HasColumnType("float");

                    b.Property<double>("priceProductFor50")
                        .HasColumnType("float");

                    b.Property<string>("productDecsciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titleProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            productID = 1,
                            Author = "Billy Spark",
                            CategoryId = 1,
                            ISBN = "SWD9999001",
                            listPrice = 99.0,
                            priceProduct = 90.0,
                            priceProductFor100 = 80.0,
                            priceProductFor50 = 85.0,
                            productDecsciption = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            titleProduct = "Fortune of Time"
                        },
                        new
                        {
                            productID = 2,
                            Author = "Nancy Hoover",
                            CategoryId = 1,
                            ISBN = "CAW777777701",
                            listPrice = 40.0,
                            priceProduct = 30.0,
                            priceProductFor100 = 20.0,
                            priceProductFor50 = 25.0,
                            productDecsciption = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            titleProduct = "Dark Skies"
                        },
                        new
                        {
                            productID = 3,
                            Author = "Julian Button",
                            CategoryId = 2,
                            ISBN = "RITO5555501",
                            listPrice = 55.0,
                            priceProduct = 50.0,
                            priceProductFor100 = 35.0,
                            priceProductFor50 = 40.0,
                            productDecsciption = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            titleProduct = "Vanish in the Sunset"
                        },
                        new
                        {
                            productID = 4,
                            Author = "Abby Muscles",
                            CategoryId = 2,
                            ISBN = "WS3333333301",
                            listPrice = 70.0,
                            priceProduct = 65.0,
                            priceProductFor100 = 55.0,
                            priceProductFor50 = 60.0,
                            productDecsciption = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            titleProduct = "Cotton Candy"
                        },
                        new
                        {
                            productID = 5,
                            Author = "Ron Parker",
                            CategoryId = 3,
                            ISBN = "SOTJ1111111101",
                            listPrice = 30.0,
                            priceProduct = 27.0,
                            priceProductFor100 = 20.0,
                            priceProductFor50 = 25.0,
                            productDecsciption = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            titleProduct = "Rock in the Ocean"
                        },
                        new
                        {
                            productID = 6,
                            Author = "Laura Phantom",
                            CategoryId = 3,
                            ISBN = "FOT000000001",
                            listPrice = 25.0,
                            priceProduct = 23.0,
                            priceProductFor100 = 20.0,
                            priceProductFor50 = 22.0,
                            productDecsciption = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            titleProduct = "Leaves and Wonders"
                        });
                });

            modelBuilder.Entity("BulkyBook.Models.Product", b =>
                {
                    b.HasOne("BulkyBook.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
